# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ff4126b96a9ff2ff87ddcff1b3c5efdecce5de39a7a704fc37c707a14978e3a23da9b011af9fc8169c12a7ec5fa00af0f78fd533345fd5a9af0d2261d071a03

test:
  secret_key_base: 2d88c49a1c083f8891120db2a790abac05513d0567e001ba7505c4bcfad1ec29ab401a1ae820bc2821342fe7c9d813a0fa7118196ed79a72a467722022bae8cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
